---
x-healthcheck: &healthcheck
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 15s

x-healthy: &healthy
  condition: service_healthy

networks:
  traefik-ingress:
    external: true
  internal:
    external: false

services:
  frontend:
    image: ${FRONTEND_IMAGE}
    container_name: zadachnik__frontend
    healthcheck:
      <<: *healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:80"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.entrypoints=webSecure
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)&&Host(`${HOST}`)
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=letsEncrypt
      - traefik.http.services.frontend.loadbalancer.server.port=80
    networks:
      - traefik-ingress
  backend:
    image: ${BACKEND_IMAGE}
    container_name: zadachnik__backend
    environment:
      - POSTGRES_HOST=zadachnik__db:5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TTL=${JWT_ACCESS_TTL}
      - JWT_REFRESH_TTL=${JWT_REFRESH_TTL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.entrypoints=webSecure
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)&&Host(`${HOST}`)
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=letsEncrypt
      - traefik.http.services.backend.loadbalancer.server.port=8080
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - traefik-ingress
      - internal
  db:
    image: ${POSTGRES_IMAGE}
    container_name: zadachnik__db
    healthcheck:
      <<: *healthcheck
      start_period: 1s
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal
  ingress:
    image: ${TRAEFIK_IMAGE}
    container_name: zadachnik__ingress
    ports:
      - 80:80
      - 443:443
      - 8001:8001
    labels:
      - "traefik.enable=false"
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/letsEncrypt:/letsEncrypt
    networks:
      - traefik-ingress

volumes:
  pgdata:
    driver: local
