- name: Prepare user
  hosts: staging
  become: true
  tasks:
    - name: Make sure zadachnik user exists
      ansible.builtin.user:
        name: infsystem-zadachnik
        groups: 
          - docker
          - sudo
    - name: Make sure directory for is exists
      ansible.builtin.file:
        dest: /opt/is
        owner: infsystem-zadachnik
        group: infsystem-zadachnik
        state: directory
        recurse: true
- name: Deploy
  hosts: staging
  become_user: infsystem-zadachnik
  become: True
  vars:
    staging_host: zadachnik.efedorov.spb.su
    registry_uri: fegor04
  tasks:
    - name: Clone git repo
      become_user: infsystem-zadachnik
      ansible.builtin.git:
        dest: /opt/is/zadachnik
        repo: https://github.com/FEgor04/is-course-work.git
        version: main
        force: true
    - name: Set git repo permissions
      ansible.builtin.file:
        dest: /opt/is/zadachnik
        owner: infsystem-zadachnik
        group: infsystem-zadachnik
        state: directory
        recurse: true
    - name: Set permissions for acme.json
      ansible.builtin.file:
        dest: /opt/is/zadachnik/traefik/letsEncrypt/acme.json
        state: file
        owner: infsystem-zadachnik
        group: infsystem-zadachnik
        mode: u=rw,go-rwx
    - name: Copy .env
      ansible.builtin.template:
        src: ./env.j2
        dest: /opt/is/zadachnik/.env
        owner: infsystem-zadachnik
        group: infsystem-zadachnik
        mode: u=rw,go-rwx
    - name: Restart docker services
      ansible.builtin.command:
        chdir: /opt/is/zadachnik
        cmd: make prod-up
