name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '22.5.x'
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Build
      run: pnpm run build
    - name: Linter
      run: pnpm run lint

  build-backend:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
     
    - name: Build
      run: ./gradlew build

    - name: Jacoco Report to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.7.1
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Code Coverage
        update-comment: true

